version: '3'
services:
  test-db:
    image: postgres
    environment:
      POSTGRES_DB: step-warrior-api-test
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3

  test:
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://test-db:5432/step-warrior-api-test?sslmode=disable
    links:
      - test-db
    depends_on:
      - test-db
    command: make test
