apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: step-warrior
  labels:
    #Project ID
    app: step-warrior
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: step-warrior
    spec:
      containers:
        - name: step-warrior
          image: us.gcr.io/step-warrior/step-warrior
          imagePullPolicy: Always
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: step-warrior-db-url
                key: db-url
          - name: NEW_RELIC_LOG
            value: stdout
          ports:
          - containerPort: 8080
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.09
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=step-warrior:us-central1:step-warrior-db=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
